// PluhMath Games Database - Sleek Minimalist Edition
const GAMES_DB = [
  {
    id: 'undertale',
    slug: 'undertale',
    url: 'undertale.html',
    title: 'Undertale',
    category: 'RPG & Story',
    categorySlug: 'rpg',
    categories: ['rpg', 'arcade', 'skill'],
    rating: '5.0',
    plays: '520K',
    tags: ['RPG', 'Undertale', 'Sans', 'Bullet Hell', 'Story', 'Retro'],
    desc: 'The acclaimed indie RPG masterpiece. Dodge bones and blasters in the legendary Sans boss encounter, navigate dialogue, and survive with your soul intact.',
    howToPlay: 'Use Arrow Keys to dodge bones, blue attacks, and gaster blasters. Watch your soul gravity in blue/red modes. Select Fight, Act, Item, or Mercy on your turn!',
    controls: [
      { key: 'Arrow Keys', desc: 'Move / Dodge heart soul' },
      { key: 'Z / Enter', desc: 'Confirm / Attack' },
      { key: 'X / Shift', desc: 'Cancel / Focus soul speed' },
      { key: 'C / Ctrl', desc: 'Menu / Info' }
    ],
    gamePath: 'games/Undertale/Undertale-main/index.html',
    icon: '❤️',
    badge: 'LEGENDARY',
    badgeColor: 'rgba(239, 68, 68, 0.9)',
    thumbnail: 'https://raw.githubusercontent.com/jcw87/c2-sans-fight/master/icon-256.png',
    bgGradient: 'linear-gradient(135deg, #111116, #1f1b29)'
  },
  {
    id: 'deltarune',
    slug: 'deltarune',
    url: 'deltarune.html',
    title: 'Deltarune',
    category: 'RPG & Story',
    categorySlug: 'rpg',
    categories: ['rpg', 'arcade', 'skill'],
    rating: '5.0',
    plays: '480K',
    tags: ['RPG', 'Deltarune', 'Toby Fox', 'Story', 'Bullet Hell', 'Kris'],
    desc: 'Toby Fox’s parallel story to Undertale. Explore the mysterious Dark World with Kris and Susie, graze bullets for TP, and conquer intense encounters.',
    howToPlay: 'Control your heart soul during enemy attack phases. Graze bullets closely without touching to build Tension Points (TP) for powerful Spells and Acts.',
    controls: [
      { key: 'Arrow Keys', desc: 'Move / Navigate' },
      { key: 'Z / Enter', desc: 'Confirm / Interact' },
      { key: 'X / Shift', desc: 'Cancel / Run' },
      { key: 'C / Ctrl', desc: 'Menu' }
    ],
    gamePath: 'games/Deltarune/index.html',
    icon: '🔷',
    badge: 'POPULAR',
    badgeColor: 'rgba(0, 240, 255, 0.9)',
    thumbnail: '',
    bgGradient: 'linear-gradient(135deg, #090e1f, #151e36)'
  },
  {
    id: 'pluhshooter',
    slug: 'pluhshooter',
    url: 'pluhshooter.html',
    title: 'PluhShooter.io',
    category: '3D & FPS',
    categorySlug: '3d',
    categories: ['3d', 'action', 'arcade'],
    rating: '4.9',
    plays: '145K',
    tags: ['3D', 'Voxel', 'FPS', 'Multiplayer', 'Zombies'],
    desc: 'Fast-paced 3D voxel first-person shooter. Battle AI bots or players in Free For All and Team Deathmatch, or survive endless waves of zombies.',
    howToPlay: 'Eliminate opponents to earn score and climb the leaderboard. Keep moving, aim for headshots, and switch weapons according to combat range.',
    controls: [
      { key: 'WASD', desc: 'Move character' },
      { key: 'Mouse', desc: 'Aim & look around' },
      { key: 'Left Click', desc: 'Fire weapon' },
      { key: 'Right Click', desc: 'Aim Down Sights (ADS)' },
      { key: 'Space', desc: 'Jump' },
      { key: 'Shift', desc: 'Sprint' },
      { key: '1 - 4', desc: 'Switch weapons' },
      { key: 'R', desc: 'Reload weapon' },
      { key: 'Esc', desc: 'Pause / Release mouse lock' }
    ],
    gamePath: 'games/PluhShooter.io/index.html',
    icon: '🔫',
    badge: '3D VOXEL',
    badgeColor: 'rgba(139, 92, 246, 0.9)',
    thumbnail: '',
    bgGradient: 'linear-gradient(135deg, #0f1322, #182035)'
  },
  {
    id: 'run3',
    slug: 'run-3',
    url: 'run-3.html',
    title: 'Run 3',
    category: 'Runner & Rhythm',
    categorySlug: 'runner',
    categories: ['runner', 'skill', '3d'],
    rating: '4.9',
    plays: '390K',
    tags: ['Runner', '3D', 'Space', 'Classic', 'Alien'],
    desc: 'The iconic galaxy runner. Sprint, jump, and rotate through floating space tunnels while dodging falling crumbling tiles and unlocking alien characters.',
    howToPlay: 'Guide your alien through floating 3D tunnels in deep space. Moving left or right rotates the entire tunnel, letting you run on walls or ceilings.',
    controls: [
      { key: 'Arrow Keys / A, D', desc: 'Move left and right' },
      { key: 'Space / Up Arrow', desc: 'Jump over gaps' },
      { key: 'P', desc: 'Pause game' },
      { key: 'R', desc: 'Reset level' }
    ],
    gamePath: 'games/Run3/index.html',
    icon: '🏃‍♂️',
    badge: 'CLASSIC',
    badgeColor: 'rgba(245, 158, 11, 0.9)',
    thumbnail: 'games/Run3/img/menu/Run3.png',
    bgGradient: 'linear-gradient(135deg, #090e1a, #131b2d)'
  },
  {
    id: 'geometry-dash',
    slug: 'geometry-dash',
    url: 'geometry-dash.html',
    title: 'Geometry Dash Subzero',
    category: 'Runner & Rhythm',
    categorySlug: 'runner',
    categories: ['runner', 'skill', 'arcade'],
    rating: '4.9',
    plays: '280K',
    tags: ['Rhythm', 'Platformer', 'Music', 'Neon', 'Hard'],
    desc: 'Jump, fly, and flip your way through dangerous neon subzero obstacles synced to electrifying EDM beats in this upgraded edition.',
    howToPlay: 'Time your jumps precisely to the rhythm of the music. Avoid spikes, saw blades, and obstacles. One single mistake sends you back to the start!',
    controls: [
      { key: 'Space / Up Arrow', desc: 'Jump / Fly' },
      { key: 'Left Click', desc: 'Jump / Fly' },
      { key: 'P', desc: 'Pause game' }
    ],
    gamePath: 'Scratch/GeometryDashSubzeroPLM/index.html',
    icon: '⚡',
    badge: 'RHYTHM',
    badgeColor: 'rgba(236, 72, 153, 0.9)',
    thumbnail: '',
    bgGradient: 'linear-gradient(135deg, #071722, #0d273a)'
  },
  {
    id: 'pluhus',
    slug: 'pluhus',
    url: 'pluhus.html',
    title: 'PluhUs: Browser Edition',
    category: 'Skill & Strategy',
    categorySlug: 'strategy',
    categories: ['strategy', 'arcade', 'action'],
    rating: '4.7',
    plays: '165K',
    tags: ['Among Us', 'Impostor', 'Sabotage', '2D', 'Casual'],
    desc: 'Custom 2D Among Us browser game engine featuring impostor sabotages, door lockdowns, emergency meetings, ventilation tunnels, and sneaky kills.',
    howToPlay: 'Choose your role! As crewmate, complete tasks around the spaceship. As Impostor, sabotage systems, crawl through vents, and eliminate crew without getting caught.',
    controls: [
      { key: 'WASD / Arrow Keys', desc: 'Move character' },
      { key: 'Space', desc: 'Use / Interact' },
      { key: 'F', desc: 'Open Sabotage Map' },
      { key: 'E', desc: 'Kill (Impostor only)' },
      { key: 'V', desc: 'Vent (Impostor only)' },
      { key: 'R', desc: 'Report fallen crewmate' }
    ],
    gamePath: 'games/PluhUs/index.html',
    icon: '🚀',
    badge: 'STEALTH',
    badgeColor: 'rgba(239, 68, 68, 0.85)',
    thumbnail: 'games/PluhUs/Stand_mogus.png',
    bgGradient: 'linear-gradient(135deg, #200909, #381212)'
  },
  {
    id: 'drift-boss',
    slug: 'drift-boss',
    url: 'drift-boss.html',
    title: 'Drift Boss',
    category: 'Skill & Strategy',
    categorySlug: 'skill',
    categories: ['skill', 'runner', 'arcade', '3d'],
    rating: '4.8',
    plays: '215K',
    tags: ['Drifting', 'Car', 'Arcade', 'Timing', 'High Score'],
    desc: 'Endless 3D one-click drifting arcade game. Steer around tricky sharp turns, navigate pitfalls, and collect coins to unlock customizable cars.',
    howToPlay: 'Press and hold to drift right; release to drift left. Anticipate upcoming curves and time your turns with pinpoint precision to keep from falling off!',
    controls: [
      { key: 'Left Click / Space', desc: 'Hold to steer right, release to steer left' }
    ],
    gamePath: 'games/drift-boss/index.html',
    icon: '🏎️',
    badge: 'ARCADE',
    badgeColor: 'rgba(16, 185, 129, 0.85)',
    thumbnail: 'https://738501629-461082748261058427.preview.editmysite.com/uploads/b/139890129-817510652323129407/files/media/graphics/splash/mobile/cover-start.jpg',
    bgGradient: 'linear-gradient(135deg, #14110b, #241f14)'
  }
];

// Helper to get game by id or slug
function getGameById(idOrSlug) {
  return GAMES_DB.find(g => g.id === idOrSlug || g.slug === idOrSlug);
}
